kuduMasterAddresses: ["localhost"]
kuduTSInstance: "ktsd"

server:
  type: default
  applicationContextPath: "/api"
  applicationConnectors:
    - type: http
      port: 4242

logging:
  level: INFO
  loggers:
    org.kududb.ts: INFO

  appenders:
    - type: console
    - type: file
      threshold: DEBUG
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB

bench:
  #ktsdHost: "kudu-ts-1.vpc.cloudera.com"
  ktsdHost: "localhost"
  ktsdPort: 4242
  metrics: ["loadavg.1min", "requestCount", "errorCount"]
  tags:
    host: ["web01", "web02", "web03",
           "db01", "db02", "db03"]
    dc: ["us-east", "us-west", "asia"]

  #start: 10000000
  #metrics: ["loadavg.1min"]
  #tags:
    #dc: ["east"]
  sampleFrequency: 1
  httpClient:
    keepAlive: "10s"
    timeout: "10s"
